### ISSUE TITLE
Anonymity by default, but with disclosable handles

### ISSUE THREAD

**Issue by King-Mob** [Wobbly-App/techno-syndicalism#13]

**Comment by marcaaron** [comment]
So guessing things like email would be required for sign up but be obscured from the public API. How about some kind of name generator that picks a default username that can be updated. And some sort of messaging that reminds the user that anyone can join the group. Which brings up another point... can anyone join a group?

**Comment by King-Mob** [comment]
I like the name generator idea e.g. pick randomly from a table of adjectives and nouns, and then you can request a reroll at any time maybe

**Comment by marcaaron** [comment]
Just added a random name generator. Can add a re-roll feature once the UI / front end api starts coming together.
